// Generated by gencpp from file udemy_cpp_pkg/OddEvencheckResponse.msg
// DO NOT EDIT!


#ifndef UDEMY_CPP_PKG_MESSAGE_ODDEVENCHECKRESPONSE_H
#define UDEMY_CPP_PKG_MESSAGE_ODDEVENCHECKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace udemy_cpp_pkg
{
template <class ContainerAllocator>
struct OddEvencheckResponse_
{
  typedef OddEvencheckResponse_<ContainerAllocator> Type;

  OddEvencheckResponse_()
    : answer()  {
    }
  OddEvencheckResponse_(const ContainerAllocator& _alloc)
    : answer(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _answer_type;
  _answer_type answer;





  typedef boost::shared_ptr< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OddEvencheckResponse_

typedef ::udemy_cpp_pkg::OddEvencheckResponse_<std::allocator<void> > OddEvencheckResponse;

typedef boost::shared_ptr< ::udemy_cpp_pkg::OddEvencheckResponse > OddEvencheckResponsePtr;
typedef boost::shared_ptr< ::udemy_cpp_pkg::OddEvencheckResponse const> OddEvencheckResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator1> & lhs, const ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator2> & rhs)
{
  return lhs.answer == rhs.answer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator1> & lhs, const ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace udemy_cpp_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7e708f879c94bb931716d8f4f130f30";
  }

  static const char* value(const ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7e708f879c94bb9ULL;
  static const uint64_t static_value2 = 0x31716d8f4f130f30ULL;
};

template<class ContainerAllocator>
struct DataType< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "udemy_cpp_pkg/OddEvencheckResponse";
  }

  static const char* value(const ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string answer \n"
"\n"
"\n"
;
  }

  static const char* value(const ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OddEvencheckResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::udemy_cpp_pkg::OddEvencheckResponse_<ContainerAllocator>& v)
  {
    s << indent << "answer: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UDEMY_CPP_PKG_MESSAGE_ODDEVENCHECKRESPONSE_H
