// Generated by gencpp from file udemy_cpp_pkg/OddEvencheckRequest.msg
// DO NOT EDIT!


#ifndef UDEMY_CPP_PKG_MESSAGE_ODDEVENCHECKREQUEST_H
#define UDEMY_CPP_PKG_MESSAGE_ODDEVENCHECKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace udemy_cpp_pkg
{
template <class ContainerAllocator>
struct OddEvencheckRequest_
{
  typedef OddEvencheckRequest_<ContainerAllocator> Type;

  OddEvencheckRequest_()
    : number(0)  {
    }
  OddEvencheckRequest_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef int32_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OddEvencheckRequest_

typedef ::udemy_cpp_pkg::OddEvencheckRequest_<std::allocator<void> > OddEvencheckRequest;

typedef boost::shared_ptr< ::udemy_cpp_pkg::OddEvencheckRequest > OddEvencheckRequestPtr;
typedef boost::shared_ptr< ::udemy_cpp_pkg::OddEvencheckRequest const> OddEvencheckRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator1> & lhs, const ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator1> & lhs, const ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace udemy_cpp_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2474488a3908093ec1307bdd5b35815e";
  }

  static const char* value(const ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2474488a3908093eULL;
  static const uint64_t static_value2 = 0xc1307bdd5b35815eULL;
};

template<class ContainerAllocator>
struct DataType< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "udemy_cpp_pkg/OddEvencheckRequest";
  }

  static const char* value(const ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 number \n"
;
  }

  static const char* value(const ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OddEvencheckRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::udemy_cpp_pkg::OddEvencheckRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UDEMY_CPP_PKG_MESSAGE_ODDEVENCHECKREQUEST_H
