// Generated by gencpp from file udemy_cpp_pkg/TurnCamera.msg
// DO NOT EDIT!


#ifndef UDEMY_CPP_PKG_MESSAGE_TURNCAMERA_H
#define UDEMY_CPP_PKG_MESSAGE_TURNCAMERA_H

#include <ros/service_traits.h>


#include <udemy_cpp_pkg/TurnCameraRequest.h>
#include <udemy_cpp_pkg/TurnCameraResponse.h>


namespace udemy_cpp_pkg
{

struct TurnCamera
{

typedef TurnCameraRequest Request;
typedef TurnCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurnCamera
} // namespace udemy_cpp_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::udemy_cpp_pkg::TurnCamera > {
  static const char* value()
  {
    return "48e9c72001527a85ebcc47fcec8f9237";
  }

  static const char* value(const ::udemy_cpp_pkg::TurnCamera&) { return value(); }
};

template<>
struct DataType< ::udemy_cpp_pkg::TurnCamera > {
  static const char* value()
  {
    return "udemy_cpp_pkg/TurnCamera";
  }

  static const char* value(const ::udemy_cpp_pkg::TurnCamera&) { return value(); }
};


// service_traits::MD5Sum< ::udemy_cpp_pkg::TurnCameraRequest> should match
// service_traits::MD5Sum< ::udemy_cpp_pkg::TurnCamera >
template<>
struct MD5Sum< ::udemy_cpp_pkg::TurnCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::udemy_cpp_pkg::TurnCamera >::value();
  }
  static const char* value(const ::udemy_cpp_pkg::TurnCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::udemy_cpp_pkg::TurnCameraRequest> should match
// service_traits::DataType< ::udemy_cpp_pkg::TurnCamera >
template<>
struct DataType< ::udemy_cpp_pkg::TurnCameraRequest>
{
  static const char* value()
  {
    return DataType< ::udemy_cpp_pkg::TurnCamera >::value();
  }
  static const char* value(const ::udemy_cpp_pkg::TurnCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::udemy_cpp_pkg::TurnCameraResponse> should match
// service_traits::MD5Sum< ::udemy_cpp_pkg::TurnCamera >
template<>
struct MD5Sum< ::udemy_cpp_pkg::TurnCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::udemy_cpp_pkg::TurnCamera >::value();
  }
  static const char* value(const ::udemy_cpp_pkg::TurnCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::udemy_cpp_pkg::TurnCameraResponse> should match
// service_traits::DataType< ::udemy_cpp_pkg::TurnCamera >
template<>
struct DataType< ::udemy_cpp_pkg::TurnCameraResponse>
{
  static const char* value()
  {
    return DataType< ::udemy_cpp_pkg::TurnCamera >::value();
  }
  static const char* value(const ::udemy_cpp_pkg::TurnCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UDEMY_CPP_PKG_MESSAGE_TURNCAMERA_H
